In [11]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv(
    "messy_edu_growth_99_columns - messy_edu_growth_99_columns.csv.csv"
)

In [13]:
df.shape

(49000, 99)

In [14]:
df.head()

,roll_no,full_name,class_section,overall_attendance_pct,theory_attendance_pct,practical_attendance_pct,previous_cgpa,medical_leave_days,society_participation_pc,sports_activity_level,...,lab_ds_submission_delay_hours,lab_python_execution_score,lab_python_viva_score,lab_python_submission_delay_hours,lab_coa_execution_score,lab_coa_viva_score,lab_coa_submission_delay_hours,lab_cyber_execution_score,lab_cyber_viva_score,lab_cyber_submission_delay_hours
0,210029053348,Aarav Shah,CS-DS,38,42.5,35.9,6.47,3.0,71.5,high,...,18.6,24.1,12.8,20.3,26.3,17.4,91.3,22.6,NaN,31.2
1,210029035828,Kabir Verma,CS-DS,70.3,68.1,77.9,8.30,0.0,22.7,MODERATE,...,36.4,38.4,19.5,13.4,32.4,26.2,14.9,31.9,17.3,NaN
2,210029039616,isha kumar,IT-A,53.60%,49.6,59.6,NaN,3.0,26.9,NaN,...,14.0,37.5,22.7,17.8,38.7,21.7,19.7,33.6,22.9,8.5
3,210029036528,Kabir Bhat,CS-DS,91.1,88.0,93.6,9.73,3.0,41.3,HIGH,...,21.4,42.2,25.2,10.5,47.7,27.0,16.0,50.0,27.9,5.7
4,210029010644,Aditya Das,CSE-A,76.4,67.1,75.3,7.97,2.0,9.2,LOW,...,13.0,42.2,22.4,10.3,36.1,24.0,17.2,42.6,26.3,25.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46500 entries, 0 to 48999
Data columns (total 99 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   roll_no                            46500 non-null  int64
 1   full_name                          44206 non-null  object
 2   class_section                      44255 non-null  object
 3   overall_attendance_pct             44180 non-null  object
 4   theory_attendance_pct              44157 non-null  float64
 5   practical_attendance_pct           44211 non-null  float64
 6   previous_cgpa                      44141 non-null  float64
 7   medical_leave_days                 44081 non-null  float64
 8   society_participation_pc           44245 non-null  float64
 9   sports_activity_level              33237 non-null  object
 10  final_semester_grade               44308 non-null  float64
 11  coa_attendance_pct                 44146 non-null  float64
 12  maths4_attendance_pct              44170 non-null  float64
 13  dstl_attendance_pct                44265 non-null  float64
 14  ds_attendance_pct                  44194 non-null  float64
 15  python_attendance_pct              44191 non-null  float64
 16  cyber_attendance_pct               44242 non-null  float64
 17  lab_ds_attendance_pct              44212 non-null  float64
 18  lab_python_attendance_pct          44144 non-null  float64
 19  lab_coa_attendance_pct             44115 non-null  float64
 20  lab_cyber_attendance_pct           44162 non-null  float64
 21  coa_st1_marks                      44166 non-null  float64
 22  coa_st2_marks                      44203 non-null  float64
 23  coa_put_marks                      44187 non-null  float64
 24  coa_unit_1_marks                   44203 non-null  float64
 25  coa_unit_2_marks                   44234 non-null  float64
 26  coa_unit_3_marks                   44178 non-null  float64
 27  coa_unit_4_marks                   44192 non-null  float64
 28  coa_unit_5_marks                   44123 non-null  float64
 29  coa_assignment_score               44182 non-null  float64
 30  coa_assignment_delay_hours         44156 non-null  float64
 31  coa_quiz_score                     44191 non-null  float64
 32  maths4_st1_marks                   44241 non-null  float64
 33  maths4_st2_marks                   44157 non-null  float64
 34  maths4_put_marks                   44193 non-null  float64
 35  maths4_unit_1_marks                44174 non-null  float64
 36  maths4_unit_2_marks                44096 non-null  float64
 37  maths4_unit_3_marks                44165 non-null  float64
 38  maths4_unit_4_marks                44155 non-null  float64
 39  maths4_unit_5_marks                44178 non-null  float64
 40  maths4_assignment_score            44106 non-null  float64
 41  maths4_assignment_delay_hours      44191 non-null  float64
 42  maths4_quiz_score                  44142 non-null  float64
 43  dstl_st1_marks                     44165 non-null  float64
 44  dstl_st2_marks                     44037 non-null  float64
 45  dstl_put_marks                     44233 non-null  float64
 46  dstl_unit_1_marks                  44075 non-null  float64
 47  dstl_unit_2_marks                  44157 non-null  float64
 48  dstl_unit_3_marks                  44122 non-null  float64
 49  dstl_unit_4_marks                  44171 non-null  float64
 50  dstl_unit_5_marks                  44199 non-null  float64
 51  dstl_assignment_score              44168 non-null  float64
 52  dstl_assignment_delay_hours        44117 non-null  float64
 53  dstl_quiz_score                    44156 non-null  float64
 54  ds_st1_marks                       44200 non-null  float64
 55  ds_st2_marks                       44278 non-null  float64
 56  ds_put_marks                       44079 non-null  float64
 57  ds_unit_1_marks                    44142 non-null  float64
 58  ds_unit_2_marks                    44134 non-null  float64
 59  ds_unit_3_marks                    44215 non-null  float64
 60  ds_unit_4_marks                    44178 non-null  float64
 61  ds_unit_5_marks                    44260 non-null  float64
 62  ds_assignment_score                44137 non-null  float64
 63  ds_assignment_delay_hours          44125 non-null  float64
 64  ds_quiz_score                      44155 non-null  float64
 65  python_st1_marks                   44142 non-null  float64
 66  python_st2_marks                   44077 non-null  float64
 67  python_put_marks                   44152 non-null  float64
 68  python_unit_1_marks                44231 non-null  float64
 69  python_unit_2_marks                44173 non-null  float64
 70  python_unit_3_marks                44107 non-null  float64
 71  python_unit_4_marks                44171 non-null  float64
 72  python_unit_5_marks                44125 non-null  float64
 73  python_assignment_score            44165 non-null  float64
 74  python_assignment_delay_hours      44274 non-null  float64
 75  python_quiz_score                  44158 non-null  float64
 76  cyber_st1_marks                    44174 non-null  float64
 77  cyber_st2_marks                    44263 non-null  float64
 78  cyber_put_marks                    44111 non-null  float64
 79  cyber_unit_1_marks                 44235 non-null  float64
 80  cyber_unit_2_marks                 44189 non-null  float64
 81  cyber_unit_3_marks                 44165 non-null  float64
 82  cyber_unit_4_marks                 44177 non-null  float64
 83  cyber_unit_5_marks                 44283 non-null  float64
 84  cyber_assignment_score             44291 non-null  float64
 85  cyber_assignment_delay_hours       44273 non-null  float64
 86  cyber_quiz_score                   44195 non-null  float64
 87  lab_ds_execution_score             44147 non-null  float64
 88  lab_ds_viva_score                  44159 non-null  float64
 89  lab_ds_submission_delay_hours      44131 non-null  float64
 90  lab_python_execution_score         44190 non-null  float64
 91  lab_python_viva_score              44174 non-null  float64
 92  lab_python_submission_delay_hours  44208 non-null  float64
 93  lab_coa_execution_score            44249 non-null  float64
 94  lab_coa_viva_score                 44179 non-null  float64
 95  lab_coa_submission_delay_hours     44045 non-null  float64
 96  lab_cyber_execution_score          44158 non-null  float64
 97  lab_cyber_viva_score               44157 non-null  float64
 98  lab_cyber_submission_delay_hours   44190 non-null  float64
dtypes: float64(94), int64(1), object(4)
memory usage: 35.5+ MB

In [25]:
df.describe()

,roll_no,theory_attendance_pct,practical_attendance_pct,previous_cgpa,medical_leave_days,society_participation_pc,final_semester_grade,coa_attendance_pct,maths4_attendance_pct,dstl_attendance_pct,...,lab_ds_submission_delay_hours,lab_python_execution_score,lab_python_viva_score,lab_python_submission_delay_hours,lab_coa_execution_score,lab_coa_viva_score,lab_coa_submission_delay_hours,lab_cyber_execution_score,lab_cyber_viva_score,lab_cyber_submission_delay_hours
count,4.650000e+04,44157.000000,44211.000000,44141.000000,44081.000000,44245.000000,44308.000000,44146.000000,44170.000000,44265.000000,...,44131.000000,44190.000000,44174.000000,44208.000000,44249.000000,44179.000000,44045.000000,44158.000000,44157.000000,44190.000000
mean,2.100290e+11,70.825015,72.688297,7.999903,2.012001,20.020881,7.848134,70.723318,70.699683,70.653406,...,20.281081,35.520557,21.290096,20.253413,35.461120,21.281799,20.327022,35.459355,21.231091,20.240751
std,1.342354e+04,18.902584,18.902419,1.245628,1.423763,19.467213,1.252994,19.268079,19.321764,19.289786,...,11.523160,9.455991,5.715207,11.453932,9.428185,5.718653,11.552833,9.447856,5.720047,11.474885
min,2.100290e+11,0.300000,0.500000,2.860000,0.000000,0.000000,2.870000,0.000000,0.000000,0.000000,...,0.300000,0.000000,0.000000,0.400000,0.000000,0.000000,0.500000,0.000000,0.000000,0.100000
25%,2.100290e+11,58.200000,60.100000,7.200000,1.000000,5.800000,7.040000,58.000000,57.800000,57.900000,...,12.200000,29.300000,17.500000,12.100000,29.300000,17.500000,12.200000,29.100000,17.400000,12.100000
50%,2.100290e+11,72.600000,74.500000,8.120000,2.000000,14.000000,7.990000,72.500000,72.500000,72.400000,...,18.100000,36.500000,21.800000,18.100000,36.400000,21.800000,18.100000,36.300000,21.800000,18.100000
75%,2.100290e+11,85.500000,87.600000,8.910000,3.000000,28.000000,8.800000,85.700000,85.900000,85.800000,...,25.900000,42.800000,25.700000,25.800000,42.600000,25.700000,26.000000,42.700000,25.600000,25.900000
max,2.100291e+11,100.000000,100.000000,15.500000,11.000000,100.000000,10.000000,100.000000,100.000000,100.000000,...,120.000000,50.000000,30.000000,120.000000,50.000000,30.000000,120.000000,50.000000,30.000000,120.000000

In [26]:
df.select_dtypes(include="object").nunique()

full_name                  450
class_section                9
overall_attendance_pct    1669
sports_activity_level        6
dtype: int64

In [27]:
print("Class Sections:")
print(df["class_section"].value_counts(dropna=False))

print("\nSports Activity Levels:")
print(df["sports_activity_level"].value_counts(dropna=False))

Class Sections:
class_section
IT-A     4957
CSE-B    4944
CS-DS    4942
CS-AI    4919
CSE-A    4918
IT-a     4917
CSE-C    4901
IT-B     4891
cse-a    4866
NaN      2245
Name: count, dtype: int64

Sports Activity Levels:
sports_activity_level
NaN         13263
moderate     5633
high         5562
low          5543
LOW          5535
HIGH         5507
MODERATE     5457
Name: count, dtype: int64

In [29]:
df["class_section"] = df["class_section"].str.upper().str.strip()

df["sports_activity_level"] = df["sports_activity_level"].str.upper().str.strip()

In [30]:
print("Class Sections:")
print(df["class_section"].value_counts(dropna=False))

print("\nSports Activity Levels:")
print(df["sports_activity_level"].value_counts(dropna=False))

Class Sections:
class_section
IT-A     9874
CSE-A    9784
CSE-B    4944
CS-DS    4942
CS-AI    4919
CSE-C    4901
IT-B     4891
NaN      2245
Name: count, dtype: int64

Sports Activity Levels:
sports_activity_level
NaN         13263
MODERATE    11090
LOW         11078
HIGH        11069
Name: count, dtype: int64

In [31]:
df["overall_attendance_pct"].head(20)

0         38
1       70.3
2     53.60%
3       91.1
4       76.4
5       69.9
6       69.4
7        NaN
8       66.9
9     74.00%
10      63.4
11      29.8
12      72.8
13      86.5
14      67.5
15      93.7
16      44.7
17      73.6
18      46.3
19        51
Name: overall_attendance_pct, dtype: object

In [33]:
df["overall_attendance_pct"] = (
    df["overall_attendance_pct"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

df["overall_attendance_pct"] = pd.to_numeric(
    df["overall_attendance_pct"],
    errors="coerce"
)

In [34]:
df["overall_attendance_pct"].dtype

dtype('float64')

In [35]:
df[
    (df["overall_attendance_pct"] < 0) |
    (df["overall_attendance_pct"] > 100)
][["roll_no", "overall_attendance_pct"]]

Empty DataFrame
Columns: [roll_no, overall_attendance_pct]
Index: []

In [36]:
df["overall_attendance_pct"].isnull().sum()

np.int64(2320)

In [37]:
print("Mean:", df["overall_attendance_pct"].mean())
print("Median:", df["overall_attendance_pct"].median())

Mean: 70.94879583521956
Median: 72.6

In [38]:
attendance_median = df["overall_attendance_pct"].median()

attendance_median

72.6

In [40]:
df["overall_attendance_pct"] = df["overall_attendance_pct"].fillna(
    df["overall_attendance_pct"].median()
)

In [41]:
df["overall_attendance_pct"].isnull().sum()

np.int64(0)

In [42]:
df.isnull().sum()

roll_no                                0
full_name                           2294
class_section                       2245
overall_attendance_pct                 0
theory_attendance_pct               2343
                                    ...
lab_coa_viva_score                  2321
lab_coa_submission_delay_hours      2455
lab_cyber_execution_score           2342
lab_cyber_viva_score                2343
lab_cyber_submission_delay_hours    2310
Length: 99, dtype: int64

In [43]:
missing = df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

sports_activity_level             13263
dstl_st2_marks                     2463
lab_coa_submission_delay_hours     2455
dstl_unit_1_marks                  2425
python_st2_marks                   2423
                                  ...
python_assignment_delay_hours      2226
ds_st2_marks                       2222
cyber_unit_5_marks                 2217
cyber_assignment_score             2209
final_semester_grade               2192
Length: 97, dtype: int64

In [44]:
df[df.columns[df.isnull().any()]].select_dtypes(include="object").isnull().sum()

full_name                 2294
class_section             2245
sports_activity_level    13263
dtype: int64

In [45]:
df[df["full_name"].isnull()][["roll_no", "full_name"]].head(10)

          roll_no full_name
8    210029012530       NaN
30   210029047594       NaN
37   210029054208       NaN
43   210029023660       NaN
44   210029016013       NaN
49   210029046974       NaN
58   210029047400       NaN
76   210029012059       NaN
118  210029049011       NaN
131  210029030403       NaN

In [46]:
df["full_name"] = df["full_name"].fillna("Unknown")

In [47]:
df["full_name"].isnull().sum()

np.int64(0)

In [49]:
df[df["class_section"].isnull()][
 ["roll_no", "class_section"]].head(10)

          roll_no class_section
20   210029011599           NaN
24   210029033278           NaN
55   210029050609           NaN
59   210029028795           NaN
64   210029019384           NaN
75   210029030027           NaN
91   210029049704           NaN
113  210029052421           NaN
118  210029049011           NaN
135  210029039634           NaN

In [50]:
df["class_section"].value_counts()

class_section
IT-A     9874
CSE-A    9784
CSE-B    4944
CS-DS    4942
CS-AI    4919
CSE-C    4901
IT-B     4891
Name: count, dtype: int64

In [51]:
df["class_section"] = df["class_section"].fillna("Unknown")

In [52]:
df["class_section"].isnull().sum()

np.int64(0)

In [53]:
df.groupby("sports_activity_level")["society_participation_pc"].mean()

sports_activity_level
HIGH        19.593903
LOW         20.193968
MODERATE    20.033239
Name: society_participation_pc, dtype: float64

In [54]:
df["sports_activity_level"] = df["sports_activity_level"].fillna("UNKNOWN")

In [55]:
df["sports_activity_level"].isnull().sum()

np.int64(0)

In [56]:
df.select_dtypes(include="number").isnull().sum()

roll_no                                0
overall_attendance_pct                 0
theory_attendance_pct               2343
practical_attendance_pct            2289
previous_cgpa                       2359
                                    ...
lab_coa_viva_score                  2321
lab_coa_submission_delay_hours      2455
lab_cyber_execution_score           2342
lab_cyber_viva_score                2343
lab_cyber_submission_delay_hours    2310
Length: 96, dtype: int64

In [57]:
df["final_semester_grade"].isnull().sum()

np.int64(2192)

In [59]:
attendance_cols = [
    "theory_attendance_pct",
    "practical_attendance_pct",
    "coa_attendance_pct",
    "maths4_attendance_pct",
    "dstl_attendance_pct",
    "ds_attendance_pct",
    "python_attendance_pct",
    "cyber_attendance_pct",
    "lab_ds_attendance_pct",
    "lab_python_attendance_pct",
    "lab_coa_attendance_pct",
    "lab_cyber_attendance_pct"
]

df[attendance_cols].median()

theory_attendance_pct        72.6
practical_attendance_pct     74.5
coa_attendance_pct           72.5
maths4_attendance_pct        72.5
dstl_attendance_pct          72.4
ds_attendance_pct            72.5
python_attendance_pct        72.5
cyber_attendance_pct         72.5
lab_ds_attendance_pct        74.4
lab_python_attendance_pct    74.5
lab_coa_attendance_pct       74.5
lab_cyber_attendance_pct     74.4
dtype: float64

In [61]:
for col in attendance_cols:
 df[col] = df[col].fillna(df[col].median())

In [62]:
df[attendance_cols].isnull().sum()

theory_attendance_pct        0
practical_attendance_pct     0
coa_attendance_pct           0
maths4_attendance_pct        0
dstl_attendance_pct          0
ds_attendance_pct            0
python_attendance_pct        0
cyber_attendance_pct         0
lab_ds_attendance_pct        0
lab_python_attendance_pct    0
lab_coa_attendance_pct       0
lab_cyber_attendance_pct     0
dtype: int64

In [64]:
basic_cols = ["previous_cgpa","medical_leave_days","society_participation_pc"]
df[basic_cols].median()

previous_cgpa                8.12
medical_leave_days           2.00
society_participation_pc    14.00
dtype: float64

In [66]:
for col in basic_cols:
    df[col] = df[col].fillna(df[col].median())

In [15]:
df.columns.tolist()

['roll_no',
 'full_name',
 'class_section',
 'overall_attendance_pct',
 'theory_attendance_pct',
 'practical_attendance_pct',
 'previous_cgpa',
 'medical_leave_days',
 'society_participation_pc',
 'sports_activity_level',
 'final_semester_grade',
 'coa_attendance_pct',
 'maths4_attendance_pct',
 'dstl_attendance_pct',
 'ds_attendance_pct',
 'python_attendance_pct',
 'cyber_attendance_pct',
 'lab_ds_attendance_pct',
 'lab_python_attendance_pct',
 'lab_coa_attendance_pct',
 'lab_cyber_attendance_pct',
 'coa_st1_marks',
 'coa_st2_marks',
 'coa_put_marks',
 'coa_unit_1_marks',
 'coa_unit_2_marks',
 'coa_unit_3_marks',
 'coa_unit_4_marks',
 'coa_unit_5_marks',
 'coa_assignment_score',
 'coa_assignment_delay_hours',
 'coa_quiz_score',
 'maths4_st1_marks',
 'maths4_st2_marks',
 'maths4_put_marks',
 'maths4_unit_1_marks',
 'maths4_unit_2_marks',
 'maths4_unit_3_marks',
 'maths4_unit_4_marks',
 'maths4_unit_5_marks',
 'maths4_assignment_score',
 'maths4_assignment_delay_hours',
 'maths4_quiz_score',
 'dstl_st1_marks',
 'dstl_st2_marks',
 'dstl_put_marks',
 'dstl_unit_1_marks',
 'dstl_unit_2_marks',
 'dstl_unit_3_marks',
 'dstl_unit_4_marks',
 'dstl_unit_5_marks',
 'dstl_assignment_score',
 'dstl_assignment_delay_hours',
 'dstl_quiz_score',
 'ds_st1_marks',
 'ds_st2_marks',
 'ds_put_marks',
 'ds_unit_1_marks',
 'ds_unit_2_marks',
 'ds_unit_3_marks',
 'ds_unit_4_marks',
 'ds_unit_5_marks',
 'ds_assignment_score',
 'ds_assignment_delay_hours',
 'ds_quiz_score',
 'python_st1_marks',
 'python_st2_marks',
 'python_put_marks',
 'python_unit_1_marks',
 'python_unit_2_marks',
 'python_unit_3_marks',
 'python_unit_4_marks',
 'python_unit_5_marks',
 'python_assignment_score',
 'python_assignment_delay_hours',
 'python_quiz_score',
 'cyber_st1_marks',
 'cyber_st2_marks',
 'cyber_put_marks',
 'cyber_unit_1_marks',
 'cyber_unit_2_marks',
 'cyber_unit_3_marks',
 'cyber_unit_4_marks',
 'cyber_unit_5_marks',
 'cyber_assignment_score',
 'cyber_assignment_delay_hours',
 'cyber_quiz_score',
 'lab_ds_execution_score',
 'lab_ds_viva_score',
 'lab_ds_submission_delay_hours',
 'lab_python_execution_score',
 'lab_python_viva_score',
 'lab_python_submission_delay_hours',
 'lab_coa_execution_score',
 'lab_coa_viva_score',
 'lab_coa_submission_delay_hours',
 'lab_cyber_execution_score',
 'lab_cyber_viva_score',
 'lab_cyber_submission_delay_hours']

In [67]:
df[basic_cols].isnull().sum()

previous_cgpa               0
medical_leave_days          0
society_participation_pc    0
dtype: int64

In [69]:
coa_cols = [
    "coa_st1_marks",
    "coa_st2_marks",
    "coa_put_marks",
    "coa_unit_1_marks",
    "coa_unit_2_marks",
    "coa_unit_3_marks",
    "coa_unit_4_marks",
    "coa_unit_5_marks",
    "coa_assignment_score",
    "coa_assignment_delay_hours",
    "coa_quiz_score"
]

In [70]:
df[coa_cols].isnull().sum()

coa_st1_marks                 2334
coa_st2_marks                 2297
coa_put_marks                 2313
coa_unit_1_marks              2297
coa_unit_2_marks              2266
coa_unit_3_marks              2322
coa_unit_4_marks              2308
coa_unit_5_marks              2377
coa_assignment_score          2318
coa_assignment_delay_hours    2344
coa_quiz_score                2309
dtype: int64

In [71]:
df[coa_cols].median()

coa_st1_marks                 21.8
coa_st2_marks                 21.8
coa_put_marks                 72.9
coa_unit_1_marks              14.6
coa_unit_2_marks              14.5
coa_unit_3_marks              14.5
coa_unit_4_marks              14.5
coa_unit_5_marks              14.5
coa_assignment_score           7.3
coa_assignment_delay_hours    23.2
coa_quiz_score                 7.2
dtype: float64

In [72]:
for col in coa_cols:
    df[col] = df[col].fillna(df[col].median())

In [73]:
df[coa_cols].isnull().sum()

coa_st1_marks                 0
coa_st2_marks                 0
coa_put_marks                 0
coa_unit_1_marks              0
coa_unit_2_marks              0
coa_unit_3_marks              0
coa_unit_4_marks              0
coa_unit_5_marks              0
coa_assignment_score          0
coa_assignment_delay_hours    0
coa_quiz_score                0
dtype: int64

In [74]:
maths_cols = [
    "maths4_st1_marks",
    "maths4_st2_marks",
    "maths4_put_marks",
    "maths4_unit_1_marks",
    "maths4_unit_2_marks",
    "maths4_unit_3_marks",
    "maths4_unit_4_marks",
    "maths4_unit_5_marks",
    "maths4_assignment_score",
    "maths4_assignment_delay_hours",
    "maths4_quiz_score"
]

In [75]:
df[maths_cols].isnull().sum()

maths4_st1_marks                 2259
maths4_st2_marks                 2343
maths4_put_marks                 2307
maths4_unit_1_marks              2326
maths4_unit_2_marks              2404
maths4_unit_3_marks              2335
maths4_unit_4_marks              2345
maths4_unit_5_marks              2322
maths4_assignment_score          2394
maths4_assignment_delay_hours    2309
maths4_quiz_score                2358
dtype: int64

In [76]:
df[maths_cols].median()

maths4_st1_marks                 21.8
maths4_st2_marks                 21.8
maths4_put_marks                 72.9
maths4_unit_1_marks              14.5
maths4_unit_2_marks              14.5
maths4_unit_3_marks              14.5
maths4_unit_4_marks              14.5
maths4_unit_5_marks              14.5
maths4_assignment_score           7.2
maths4_assignment_delay_hours    23.3
maths4_quiz_score                 7.3
dtype: float64

In [78]:
for col in maths_cols:
    df[col] = df[col].fillna(df[col].median())

In [79]:
df[maths_cols].isnull().sum()

maths4_st1_marks                 0
maths4_st2_marks                 0
maths4_put_marks                 0
maths4_unit_1_marks              0
maths4_unit_2_marks              0
maths4_unit_3_marks              0
maths4_unit_4_marks              0
maths4_unit_5_marks              0
maths4_assignment_score          0
maths4_assignment_delay_hours    0
maths4_quiz_score                0
dtype: int64

In [80]:
dstl_cols = [
    "dstl_st1_marks",
    "dstl_st2_marks",
    "dstl_put_marks",
    "dstl_unit_1_marks",
    "dstl_unit_2_marks",
    "dstl_unit_3_marks",
    "dstl_unit_4_marks",
    "dstl_unit_5_marks",
    "dstl_assignment_score",
    "dstl_assignment_delay_hours",
    "dstl_quiz_score"
]

In [81]:
df[dstl_cols].isnull().sum()

dstl_st1_marks                 2335
dstl_st2_marks                 2463
dstl_put_marks                 2267
dstl_unit_1_marks              2425
dstl_unit_2_marks              2343
dstl_unit_3_marks              2378
dstl_unit_4_marks              2329
dstl_unit_5_marks              2301
dstl_assignment_score          2332
dstl_assignment_delay_hours    2383
dstl_quiz_score                2344
dtype: int64

In [82]:
df[dstl_cols].median()

dstl_st1_marks                 21.8
dstl_st2_marks                 21.8
dstl_put_marks                 73.0
dstl_unit_1_marks              14.6
dstl_unit_2_marks              14.6
dstl_unit_3_marks              14.5
dstl_unit_4_marks              14.6
dstl_unit_5_marks              14.6
dstl_assignment_score           7.3
dstl_assignment_delay_hours    23.2
dstl_quiz_score                 7.3
dtype: float64

In [83]:
for col in dstl_cols:
    df[col] = df[col].fillna(df[col].median())

In [84]:
df[dstl_cols].isnull().sum()

dstl_st1_marks                 0
dstl_st2_marks                 0
dstl_put_marks                 0
dstl_unit_1_marks              0
dstl_unit_2_marks              0
dstl_unit_3_marks              0
dstl_unit_4_marks              0
dstl_unit_5_marks              0
dstl_assignment_score          0
dstl_assignment_delay_hours    0
dstl_quiz_score                0
dtype: int64

In [85]:
ds_cols = [
    "ds_st1_marks",
    "ds_st2_marks",
    "ds_put_marks",
    "ds_unit_1_marks",
    "ds_unit_2_marks",
    "ds_unit_3_marks",
    "ds_unit_4_marks",
    "ds_unit_5_marks",
    "ds_assignment_score",
    "ds_assignment_delay_hours",
    "ds_quiz_score"
]

In [86]:
df[ds_cols].isnull().sum()

ds_st1_marks                 2300
ds_st2_marks                 2222
ds_put_marks                 2421
ds_unit_1_marks              2358
ds_unit_2_marks              2366
ds_unit_3_marks              2285
ds_unit_4_marks              2322
ds_unit_5_marks              2240
ds_assignment_score          2363
ds_assignment_delay_hours    2375
ds_quiz_score                2345
dtype: int64

In [87]:
df[ds_cols].median()

ds_st1_marks                 21.8
ds_st2_marks                 21.8
ds_put_marks                 72.9
ds_unit_1_marks              14.6
ds_unit_2_marks              14.6
ds_unit_3_marks              14.6
ds_unit_4_marks              14.6
ds_unit_5_marks              14.6
ds_assignment_score           7.3
ds_assignment_delay_hours    23.2
ds_quiz_score                 7.3
dtype: float64

In [88]:
for col in ds_cols:
    df[col] = df[col].fillna(df[col].median())

In [89]:
df[ds_cols].isnull().sum()

ds_st1_marks                 0
ds_st2_marks                 0
ds_put_marks                 0
ds_unit_1_marks              0
ds_unit_2_marks              0
ds_unit_3_marks              0
ds_unit_4_marks              0
ds_unit_5_marks              0
ds_assignment_score          0
ds_assignment_delay_hours    0
ds_quiz_score                0
dtype: int64

In [90]:
python_cols = [
    "python_st1_marks",
    "python_st2_marks",
    "python_put_marks",
    "python_unit_1_marks",
    "python_unit_2_marks",
    "python_unit_3_marks",
    "python_unit_4_marks",
    "python_unit_5_marks",
    "python_assignment_score",
    "python_assignment_delay_hours",
    "python_quiz_score"
]

In [91]:
df[python_cols].isnull().sum()

python_st1_marks                 2358
python_st2_marks                 2423
python_put_marks                 2348
python_unit_1_marks              2269
python_unit_2_marks              2327
python_unit_3_marks              2393
python_unit_4_marks              2329
python_unit_5_marks              2375
python_assignment_score          2335
python_assignment_delay_hours    2226
python_quiz_score                2342
dtype: int64

In [92]:
df[python_cols].median()

python_st1_marks                 21.9
python_st2_marks                 21.9
python_put_marks                 73.0
python_unit_1_marks              14.6
python_unit_2_marks              14.6
python_unit_3_marks              14.6
python_unit_4_marks              14.6
python_unit_5_marks              14.6
python_assignment_score           7.3
python_assignment_delay_hours    23.2
python_quiz_score                 7.3
dtype: float64

In [93]:
for col in python_cols:
    df[col] = df[col].fillna(df[col].median())

In [94]:
df[python_cols].isnull().sum()

python_st1_marks                 0
python_st2_marks                 0
python_put_marks                 0
python_unit_1_marks              0
python_unit_2_marks              0
python_unit_3_marks              0
python_unit_4_marks              0
python_unit_5_marks              0
python_assignment_score          0
python_assignment_delay_hours    0
python_quiz_score                0
dtype: int64

In [95]:
cyber_cols = [
    "cyber_st1_marks",
    "cyber_st2_marks",
    "cyber_put_marks",
    "cyber_unit_1_marks",
    "cyber_unit_2_marks",
    "cyber_unit_3_marks",
    "cyber_unit_4_marks",
    "cyber_unit_5_marks",
    "cyber_assignment_score",
    "cyber_assignment_delay_hours",
    "cyber_quiz_score"
]

In [96]:
df[cyber_cols].isnull().sum()

cyber_st1_marks                 2326
cyber_st2_marks                 2237
cyber_put_marks                 2389
cyber_unit_1_marks              2265
cyber_unit_2_marks              2311
cyber_unit_3_marks              2335
cyber_unit_4_marks              2323
cyber_unit_5_marks              2217
cyber_assignment_score          2209
cyber_assignment_delay_hours    2227
cyber_quiz_score                2305
dtype: int64

In [97]:
df[cyber_cols].median()

cyber_st1_marks                 21.9
cyber_st2_marks                 21.8
cyber_put_marks                 73.0
cyber_unit_1_marks              14.6
cyber_unit_2_marks              14.6
cyber_unit_3_marks              14.5
cyber_unit_4_marks              14.6
cyber_unit_5_marks              14.5
cyber_assignment_score           7.3
cyber_assignment_delay_hours    23.2
cyber_quiz_score                 7.3
dtype: float64

In [98]:
for col in cyber_cols:
    df[col] = df[col].fillna(df[col].median())

In [99]:
df[cyber_cols].isnull().sum()

cyber_st1_marks                 0
cyber_st2_marks                 0
cyber_put_marks                 0
cyber_unit_1_marks              0
cyber_unit_2_marks              0
cyber_unit_3_marks              0
cyber_unit_4_marks              0
cyber_unit_5_marks              0
cyber_assignment_score          0
cyber_assignment_delay_hours    0
cyber_quiz_score                0
dtype: int64

In [100]:
lab_ds_cols = [
    "lab_ds_execution_score",
    "lab_ds_viva_score",
    "lab_ds_submission_delay_hours"
]

In [101]:
df[lab_ds_cols].isnull().sum()

lab_ds_execution_score           2353
lab_ds_viva_score                2341
lab_ds_submission_delay_hours    2369
dtype: int64

In [102]:
df[lab_ds_cols].median()

lab_ds_execution_score           36.4
lab_ds_viva_score                21.8
lab_ds_submission_delay_hours    18.1
dtype: float64

In [103]:
for col in lab_ds_cols:
    df[col] = df[col].fillna(df[col].median())

In [104]:
df[lab_ds_cols].isnull().sum()

lab_ds_execution_score           0
lab_ds_viva_score                0
lab_ds_submission_delay_hours    0
dtype: int64

In [105]:
lab_python_cols = [
    "lab_python_execution_score",
    "lab_python_viva_score",
    "lab_python_submission_delay_hours"
]

In [106]:
df[lab_python_cols].isnull().sum()

lab_python_execution_score           2310
lab_python_viva_score                2326
lab_python_submission_delay_hours    2292
dtype: int64

In [107]:
df[lab_python_cols].median()

lab_python_execution_score           36.5
lab_python_viva_score                21.8
lab_python_submission_delay_hours    18.1
dtype: float64

In [108]:
for col in lab_python_cols:
    df[col] = df[col].fillna(df[col].median())

In [109]:
df[lab_python_cols].isnull().sum()

lab_python_execution_score           0
lab_python_viva_score                0
lab_python_submission_delay_hours    0
dtype: int64

In [111]:
lab_coa_cols = [
    "lab_coa_execution_score",
    "lab_coa_viva_score",
    "lab_coa_submission_delay_hours"
]

In [112]:
df[lab_coa_cols].isnull().sum()

lab_coa_execution_score           2251
lab_coa_viva_score                2321
lab_coa_submission_delay_hours    2455
dtype: int64

In [113]:
df[lab_coa_cols].median()

lab_coa_execution_score           36.4
lab_coa_viva_score                21.8
lab_coa_submission_delay_hours    18.1
dtype: float64

In [114]:
for col in lab_coa_cols:
    df[col] = df[col].fillna(df[col].median())

In [115]:
df[lab_coa_cols].isnull().sum()

lab_coa_execution_score           0
lab_coa_viva_score                0
lab_coa_submission_delay_hours    0
dtype: int64

In [116]:
lab_cyber_cols = [
    "lab_cyber_execution_score",
    "lab_cyber_viva_score",
    "lab_cyber_submission_delay_hours"
]

In [117]:
df[lab_cyber_cols].isnull().sum()

lab_cyber_execution_score           2342
lab_cyber_viva_score                2343
lab_cyber_submission_delay_hours    2310
dtype: int64

In [118]:
df[lab_cyber_cols].median()

lab_cyber_execution_score           36.3
lab_cyber_viva_score                21.8
lab_cyber_submission_delay_hours    18.1
dtype: float64

In [119]:
for col in lab_cyber_cols:
    df[col] = df[col].fillna(df[col].median())

In [120]:
df[lab_cyber_cols].isnull().sum()

lab_cyber_execution_score           0
lab_cyber_viva_score                0
lab_cyber_submission_delay_hours    0
dtype: int64

In [121]:
df.isnull().sum().sum()

np.int64(2192)

In [122]:
df.isnull().sum()[df.isnull().sum() > 0]

final_semester_grade    2192
dtype: int64

In [123]:
df["final_semester_grade"].isnull().sum()

np.int64(2192)

In [125]:
df = df.dropna(subset=["final_semester_grade"])

In [126]:
df["final_semester_grade"].isnull().sum()

np.int64(0)

In [127]:
df.shape

(44308, 99)

In [128]:
df.duplicated().sum()

np.int64(0)

In [129]:
df.dtypes

roll_no                               int64
full_name                            object
class_section                        object
overall_attendance_pct              float64
theory_attendance_pct               float64
                                     ...
lab_coa_viva_score                  float64
lab_coa_submission_delay_hours      float64
lab_cyber_execution_score           float64
lab_cyber_viva_score                float64
lab_cyber_submission_delay_hours    float64
Length: 99, dtype: object

In [130]:
df["full_name"].nunique()

451

In [131]:
df["class_section"].value_counts()

class_section
IT-A       9401
CSE-A      9353
CS-DS      4702
CSE-B      4686
CSE-C      4678
IT-B       4677
CS-AI      4671
Unknown    2140
Name: count, dtype: int64

In [132]:
df["class_section"].value_counts(normalize=True) * 100

class_section
IT-A       21.217387
CSE-A      21.109055
CS-DS      10.612079
CSE-B      10.575968
CSE-C      10.557913
IT-B       10.555656
CS-AI      10.542114
Unknown     4.829828
Name: proportion, dtype: float64

In [133]:
df["sports_activity_level"].value_counts()

sports_activity_level
UNKNOWN     12611
HIGH        10589
MODERATE    10563
LOW         10545
Name: count, dtype: int64

In [134]:
df["sports_activity_level"].value_counts(normalize=True) * 100

sports_activity_level
UNKNOWN     28.462129
HIGH        23.898619
MODERATE    23.839939
LOW         23.799314
Name: proportion, dtype: float64

In [140]:
df = df.drop(columns=["sports_activity_level"])

In [141]:
df.shape

(31697, 98)

In [142]:
df.isnull().sum().sum()

np.int64(0)

In [135]:
df["final_semester_grade"].describe()

count    44308.000000
mean         7.848134
std          1.252994
min          2.870000
25%          7.040000
50%          7.990000
75%          8.800000
max         10.000000
Name: final_semester_grade, dtype: float64